id = "tsar"
name = "TSAR Theme"
version = "0.0.2"
schema_version = 1
authors = ["x <x032205@gmail.com>"]
description = "Minimal and modern semi-transparent dark theme."
repository = "https://github.com/x032205/tsar-zed-theme"
